# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9b2bcf72bcdb31d91b68e03713b97b0efddb3cc71bcb9a91ff050a5f0476c4e45ad6f75a648c235ff93ac11128e2b66ad3c8329603788de993b176a53116386

test:
  secret_key_base: 32b658c0cb74064f2756499d7d3ba157fb293c796fb7f772aeb0a6ecfbd7eaa9fe8e4bace5ba72b814961351c2602adfb7f928d59c222f529542e3941e7400e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
